server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: abs-service
  config:
    import: optional:file:.env[.properties]
  cache:
    cache-names:
      - security/acl
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  token:
    secret: FKHkJNhkjd2dhsNiOghNi4513qjkHtyufTd3wydsjg7SAfUYFdv
  session:
    duration: 24h